### ISSUE TITLE
After updating to new version it stops working

### ISSUE THREAD

**Issue by radek-kafka** [lolouk44/xiaomi_mi_scale#55] opened 2022-10-02 13:51 UTC
Hi,

I'm very new user of the mi-scale add-on.. I have started today with configuration and have sucess in tranferring data from mi-scale.. After a while it reported to me, that there is update available on 2nd Oct 2022 .. I did the update and since the time no new messages has been received from Mi Scale 2 as I can see in MQTT .. No idea what else shall be updated. 

Part of my config: 
HCI_DEV: hci0
BLUEPY_PASSIVE_SCAN: false
MISCALE_MAC: 5C:CA:D3:C7:XX:XX
MISCALE_VERSION: 2
MQTT_PREFIX: miscale
MQTT_HOST: core-mosquitto
MQTT_USERNAME: xxxxx
MQTT_PASSWORD: yyyyy
MQTT_PORT: 1883
MQTT_RETAIN: false
MQTT_DISCOVERY: false
MQTT_DISCOVERY_PREFIX: homeassistant
MQTT_TLS_CACERTS: Path to CA Cert File
MQTT_TLS_INSECURE: false
TIME_INTERVAL: 30
USERS:
  - NAME: Radek
    SEX: male

Some ideas what could be wrong with it ? 

Many thanks
Radek

**Comment by lolouk44** [comment] 2022-10-02 14:15
Silly question: did you step on the scale to get your weight readings sent? Can you share the logs from the add-on? Have you tried a tool like mqtt Explorer to confirm data is being transferred to your mqtt broker?
Your config doesn't look right as it's missing settings for the user. Please check the doc to ensure you have the correct config

**Comment by radek-kafka** [comment] 2022-10-02 14:23
Hi .. Yes.. I have stepped on the scale (with some ballast to have different weight).. I did not posted whole config but users shall be there.. The setup of system is RBI PI 4B with Rabsbian and HA installed on top of it (not using HA OS).. 

This is the log:
-------------------------------------
2022-10-02 16:18:24 - Starting Xiaomi mi Scale...
2022-10-02 16:18:24 - Loading Config From Add-On Options...
2022-10-02 16:18:24 - Config Loaded...
-------------------------------------
2022-10-02 16:18:24 - Initialization Completed, Waiting for Scale...

nothing else.. the addon is terminating in few minutes w/o any message in the log file.. When I start watchdog it is trying to restart each few seconds.. (I'm sure something wrong at my desk/brain .. ) :)

Full config: 
HCI_DEV: hci0
BLUEPY_PASSIVE_SCAN: false
MISCALE_MAC: 5C:CA:XX:XX:XX:XX
MISCALE_VERSION: 2
MQTT_PREFIX: miscale
MQTT_HOST: core-mosquitto
MQTT_USERNAME: XXXXXXXX
MQTT_PASSWORD: XXXXXXX
MQTT_PORT: 1883
MQTT_RETAIN: true
MQTT_DISCOVERY: true
MQTT_DISCOVERY_PREFIX: homeassistant
MQTT_TLS_CACERTS: Path to CA Cert File
MQTT_TLS_INSECURE: false
TIME_INTERVAL: 30
USERS:
  - NAME: Radek
    SEX: male
    GT: 78
    LT: 90
    HEIGHT: 184
    DOB: "1972-11-03"
  - NAME: Renka
    SEX: female
    GT: 50
    LT: 77
    HEIGHT: 163
    DOB: "19XX-XX-XX"
  - NAME: Štěpánka
    SEX: female
    GT: 30
    LT: 49
    HEIGHT: 150
    DOB: "20XX-XX-XX"

(just removed some personal and device specific informations) 

MQTT Explorer has got last message: 

{"weight":81.45,"weight_unit":"kg","bmi":24.06,"basal_metabolism":1510.82,"visceral_fat":16.01,"timestamp":"2022-10-02T14:46:02+00:00"}

And nothing else after the update ..

**Comment by lolouk44** [comment] 2022-10-02 14:36
Thanks. [0.3.1](https://github.com/lolouk44/hassio-addons/releases/tag/0.3.1) being published. Update when prompted pls.

**Comment by radek-kafka** [comment] 2022-10-02 14:44
Trying to but something is still not complete in docker .. 
Receiving: Can't install lolouk44/xiaomi-mi-scale-ha-add-on:0.3.1: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.3.1&fromImage=lolouk44%2Fxiaomi-mi-scale-ha-add-on&platform=linux%2Farm64: Not Found ("manifest for lolouk44/xiaomi-mi-scale-ha-add-on:0.3.1 not found: manifest unknown: manifest unknown")

**Comment by radek-kafka** [comment] 2022-10-02 15:00
updated and and it is the same ... no sign of change ..

**Comment by lolouk44** [comment] 2022-10-02 15:01
Is the add on still rebooting ?

**Comment by radek-kafka** [comment] 2022-10-02 15:04
rebooting seems to be better now . I did not see what there was before when watchdog was active ..

**Comment by lolouk44** [comment] 2022-10-02 15:05
What do the logs show when you step on the scale?

**Comment by radek-kafka** [comment] 2022-10-02 15:11
Nothing .. is there some way to show debug information ? I'm afraid it is not getting any data from HCI0 internal BT on RBI PI4B .. New library ?

**Comment by radek-kafka** [comment] 2022-10-02 15:14
That is all I have in log: 
-------------------------------------
2022-10-02 17:02:47 - Starting Xiaomi mi Scale...
2022-10-02 17:02:47 - Loading Config From Add-On Options...
2022-10-02 17:02:47 - Config Loaded...
-------------------------------------
2022-10-02 17:02:47 - Initialization Completed, Waiting for Scale...

**Comment by radek-kafka** [comment] 2022-10-02 15:51
Hmm.. restarts with WatchDog are still there .. here is the system log: 

Oct  2 17:50:31 homeassistant 5e5bc589d7bb[660]: -------------------------------------
Oct  2 17:50:31 homeassistant 5e5bc589d7bb[660]: 2022-10-02 17:50:31 - Starting Xiaomi mi Scale...
Oct  2 17:50:31 homeassistant 5e5bc589d7bb[660]: 2022-10-02 17:50:31 - Loading Config From Add-On Options...
Oct  2 17:50:31 homeassistant 5e5bc589d7bb[660]: 2022-10-02 17:50:31 - Config Loaded...
Oct  2 17:50:31 homeassistant 5e5bc589d7bb[660]: -------------------------------------
Oct  2 17:50:31 homeassistant 5e5bc589d7bb[660]: 2022-10-02 17:50:31 - Initialization Completed, Waiting for Scale...
Oct  2 17:50:34 homeassistant 532aaac91d03[660]:
Oct  2 17:50:34 homeassistant 532aaac91d03[660]: -------------------------------------
Oct  2 17:50:34 homeassistant 532aaac91d03[660]: 2022-10-02 17:50:34 - Starting Xiaomi mi Scale...
Oct  2 17:50:34 homeassistant 532aaac91d03[660]: 2022-10-02 17:50:34 - Loading Config From Add-On Options...
Oct  2 17:50:34 homeassistant 532aaac91d03[660]: 2022-10-02 17:50:34 - Config Loaded...
Oct  2 17:50:34 homeassistant 532aaac91d03[660]: -------------------------------------
Oct  2 17:50:34 homeassistant 532aaac91d03[660]: 2022-10-02 17:50:34 - Initialization Completed, Waiting for Scale...
Oct  2 17:50:40 homeassistant 3ebf2232e327[660]:
Oct  2 17:50:40 homeassistant 3ebf2232e327[660]: -------------------------------------
Oct  2 17:50:40 homeassistant 3ebf2232e327[660]: 2022-10-02 17:50:40 - Starting Xiaomi mi Scale...
Oct  2 17:50:40 homeassistant 3ebf2232e327[660]: 2022-10-02 17:50:40 - Loading Config From Add-On Options...
Oct  2 17:50:40 homeassistant 3ebf2232e327[660]: 2022-10-02 17:50:40 - Config Loaded...
Oct  2 17:50:40 homeassistant 3ebf2232e327[660]: -------------------------------------
Oct  2 17:50:40 homeassistant 3ebf2232e327[660]: 2022-10-02 17:50:40 - Initialization Completed, Waiting for Scale...
Oct  2 17:50:44 homeassistant d367e62af004[660]:
Oct  2 17:50:44 homeassistant d367e62af004[660]: -------------------------------------
Oct  2 17:50:44 homeassistant d367e62af004[660]: 2022-10-02 17:50:44 - Starting Xiaomi mi Scale...
Oct  2 17:50:44 homeassistant d367e62af004[660]: 2022-10-02 17:50:44 - Loading Config From Add-On Options...
Oct  2 17:50:44 homeassistant d367e62af004[660]: 2022-10-02 17:50:44 - Config Loaded...
Oct  2 17:50:44 homeassistant d367e62af004[660]: -------------------------------------
Oct  2 17:50:44 homeassistant d367e62af004[660]: 2022-10-02 17:50:44 - Initialization Completed, Waiting for Scale...

**Comment by shummo** [comment] 2022-10-03 06:39
For me the same.  Everthing works until update.

```
"Running script with Docker:

Open docker-compose.yml (see below) and edit the environment to suit your configuration...
Stand up the container - docker-compose up -d"

```
I think that i should update this " - /var/run/dbus/:/var/run/dbus/:ro"
How can i update my existing docker file? (My HA runs on a Rasbperry Pi 4 > OS: Raspbian (debian11)

**Comment by insajd** [comment] 2022-10-03 08:32
Same here, addon 0.3.1 stops working immediately after starting, I could not find any errors.
Seems that common theme here is HA installation on top of debian, I have same setup as well - Supervised version.

**Comment by Radlagerkok** [comment] 2022-10-03 10:43
have the same problem
![Screenshot_2022-10-03-13-40-38-968_io homeassistant companion android](https://user-images.githubusercontent.com/67847514/193558776-50e45493-7f9b-444f-b500-c80af5d6c9d9.jpg)
![upload_2022_10_03_13_43_03_053](https://user-images.githubusercontent.com/67847514/193558779-ba80b780-d47f-4f2a-802b-7e159ebd7a98.jpg)

**Comment by lolouk44** [comment] 2022-10-03 11:42
Marking this as a duplicate of https://github.com/lolouk44/hassio-addons/issues/63 even though this issue was created prior to it, because the other issue was created in the correct repo.

**Closed by lolouk44** 2022-10-03 11:42 UTC
Labels: bug
